version: '3.8'
services:
  mysql_main:
    image: mysql:8.0
    volumes:
      - ./persistence/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./persistence/src/main/resources/data.sql:/docker-entrypoint-initdb.d/2.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_1
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    expose:
      - 3307
    networks:
      - orders-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  mysql_test:
    image: mysql:8.0
    volumes:
      - ./persistence/src/test/resources/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./persistence/src/test/resources/data.sql:/docker-entrypoint-initdb.d/2.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_1_test
      MYSQL_USER: user_test
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3308
    ports:
        - "3308:3308"
    expose:
        - 3308
    networks:
      - orders-network

  orders_web_app:
    image: orders_web_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - orders-network
    depends_on:
      mysql_main:
        condition: service_healthy

volumes:
  mysql_main:
  mysql_test:
  orders_web_app:
networks:
  orders-network: